site_name: Stream Processing Use Cases
site_description: Stream Processing Use Cases highlight some of our most popular stream processing use cases with ksqlDB

theme:
  name: material
  logo: icon-symbol-white.svg

nav:
  - Overview: index.md
  - Anomaly and Pattern Detection:
    - Detect unusual credit card activity: anomaly-detection/credit-card-activity/index.md
    - Flag unhealthy IoT devices: anomaly-detection/internet-of-things/index.md
    - Handle corrupted data from Salesforce: anomaly-detection/salesforce/index.md
  - Customer 360:
    - Match users for online dating: customer-360/online-dating/index.md
    - Understand user behavior with clickstream data: customer-360/clickstream/index.md
    - Notify passengers of flight updates: customer-360/aviation/index.md
    - Build customer loyalty programs: customer-360/loyalty-rewards/index.md
    #- Track customer journey: customer-360/customer-journey/index.md
  - Cybersecurity:
    - Detect and analyze SSH attacks: cybersecurity/SSH-attack/index.md
  - Predictive Analytics:
    - Optimize fleet management: predictive-analytics/fleet_management/index.md
    - Optimize omni-channel inventory: predictive-analytics/inventory/index.md
  - Real-time Analytics:
    - Analyze datacenter power usage: real-time-analytics/datacenter/index.md
    - Automate instant payment verifications: real-time-analytics/payment-status-check/index.md
    - Enrich orders with change data capture (CDC): real-time-analytics/denormalization/index.md
    - Build a dynamic pricing strategy: real-time-analytics/dynamic_pricing/index.md

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - toc:
      permalink: true

extra_css: [extra.css]

plugins:
  - exclude:
      glob:
        - shared/*
