site_name: Stream Processing Use Cases
site_description: Stream Processing Use Cases highlight some of our most popular stream processing use cases with ksqlDB

theme:
  name: material
  logo: icon-symbol-white.svg

nav:
  - Overview: index.md
  - Anomaly and Pattern Detection:
    - Detect unusual credit card activity: anomaly-detection/credit-card-activity/index.md
    - Flag unhealthy IoT devices: anomaly-detection/internet-of-things/index.md
    - Handle corrupted data from Salesforce: anomaly-detection/salesforce/index.md
  - Customer 360:
    - Match users for online dating: customer-360/online-dating/index.md
    - Understand user behavior with clickstream data: customer-360/clickstream/index.md
    - Notify passengers of flight updates: customer-360/aviation/index.md
    - Build customer loyalty programs: customer-360/loyalty-rewards/index.md
    #- Track customer journey: customer-360/customer-journey/index.md
    #- Modernize Messaging Workloads: customer-360/messaging-modernization/index.md
  - Cybersecurity:
    - Detect and analyze SSH attacks: cybersecurity/SSH-attack/index.md
    #- Identify firewall deny events from Splunk: cybersecurity/firewall-splunk/index.md
    #- Detect Slowloris DDoS attacks: cybersecurity/ddos/index.md
  - Predictive Analytics:
    - Optimize fleet management: predictive-analytics/fleet-management/index.md
    - Optimize omni-channel inventory: predictive-analytics/inventory/index.md
    #- Next best offer for banking: predictive-analytics/next-best-offer/index.md
    #- Machine Learning Model Retraining: predictive-analytics/model-retraining/index.md
  - Real-time Analytics:
    - Analyze datacenter power usage: real-time-analytics/datacenter/index.md
    - Automate instant payment verifications: real-time-analytics/payment-status-check/index.md
    - Enrich orders with change data capture (CDC): real-time-analytics/denormalization/index.md
    - Build a dynamic pricing strategy: real-time-analytics/dynamic-pricing/index.md
    #- Modernize mainframes for real-time: real-time-analytics/mainframe-offload/index.md
    #- Assess the success of a discount promotion: real-time-analytics/discounting/index.md
    #- Real-time logistics for a delivery fleet: real-time-analytics/logistics/index.md
    #- Filter audit logs for Splunk: real-time-analytics/filter-logs-for-splunk

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      linenums: true
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - toc:
      permalink: true

extra_css: [extra.css]

plugins:
  - exclude:
      glob:
        - shared/*
  - redirects:
      redirect_maps:
        'index.md': 'https://developer.confluent.io/tutorials/use-cases.html'
        'anomaly-detection/credit-card-activity/index.md': 'https://developer.confluent.io/tutorials/credit-card-activity/confluent.html'
        'anomaly-detection/internet-of-things/index.md': 'https://developer.confluent.io/tutorials/internet-of-things/confluent.html'
        'anomaly-detection/salesforce/index.md': 'https://developer.confluent.io/tutorials/salesforce/confluent.html'
        'customer-360/online-dating/index.md': 'https://developer.confluent.io/tutorials/online-dating/confluent.html'
        'customer-360/clickstream/index.md': 'https://developer.confluent.io/tutorials/clickstream/confluent.html'
        'customer-360/aviation/index.md': 'https://developer.confluent.io/tutorials/aviation/confluent.html'
        'customer-360/loyalty-rewards/index.md': 'https://developer.confluent.io/tutorials/loyalty-rewards/confluent.html'
        'cybersecurity/SSH-attack/index.md': 'https://developer.confluent.io/tutorials/SSH-attack/confluent.html'
        'predictive-analytics/fleet-management/index.md': 'https://developer.confluent.io/tutorials/fleet-management/confluent.html'
        'predictive-analytics/inventory/index.md': 'https://developer.confluent.io/tutorials/inventory/confluent.html'
        'real-time-analytics/datacenter/index.md': 'https://developer.confluent.io/tutorials/datacenter/confluent.html'
        'real-time-analytics/payment-status-check/index.md': 'https://developer.confluent.io/tutorials/payment-status-check/confluent.html'
        'real-time-analytics/denormalization/index.md': 'https://developer.confluent.io/tutorials/denormalization/confluent.html'
        'real-time-analytics/dynamic-pricing/index.md': 'https://developer.confluent.io/tutorials/dynamic-pricing/confluent.html'
